export const Plans = {
  Basic: {
    link: "https://buy.stripe.com/dR64js8p88b6eAwaEI",
    priceId: "price_1QWgKbL8IScSUDMo2Th24hJY",
    name: "Basic",
    price: 10,
    additionalSeatPrice: 0,
    features: ["Chatbot access only"],
    type: "seats",
  },
  BasicPlusLearningHub: {
    link: "https://buy.stripe.com/5kA6rA34O1MI1NKaEJ",
    priceId: "price_1QWgKTL8IScSUDMoeyaMtO0N",
    name: "Basic+ Learning Hub Add-on",
    price: 30,
    additionalSeatPrice: 0,
    features: ["Chatbot access", "Learning hub add-on"],
    type: "seats",
  },
  BasicPlusGenerators: {
    link: "https://buy.stripe.com/5kAaHQdJs2QM0JG7sy",
    priceId: "price_1QWgKWL8IScSUDMorKMYHWnB",
    name: "Basic+ Plan Generators Add-on",
    price: 40,
    additionalSeatPrice: 0,
    features: ["Chatbot access", "Plan generators add-on"],
    type: "seats",
  },
  Pro: {
    link: "https://buy.stripe.com/3cs6rA8p82QM6403cj",
    priceId: "price_1QWgKYL8IScSUDMo5A3ZNUo0",
    name: "Pro",
    price: 50,
    additionalSeatPrice: 0,
    features: [
      "Chatbot access",
      "Plan generators add-on",
      "Learning hub add-on",
      "Priority response time",
    ],
    type: "seats",
  },
};